global using BuildingBlocks.Enums;
global using BuildingBlocks.Messaging.Events;
global using FluentAssertions;
global using Microsoft.Extensions.Logging.Abstractions;
global using Ordering.Application.Data;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using Ordering.Infrastructure.Data;
global using Xunit;
