// <auto-generated />
using System;
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20260418172446_IncludeAmountRedeemed")]
    partial class IncludeAmountRedeemed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpirationDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModifiedOn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRedeemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedeemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10m,
                            Code = "DISCOUNT10",
                            CreatedBy = "System",
                            CreatedOn = 17040672000000000L,
                            Description = "10% off your order",
                            ExpirationDate = 17356895990000000L,
                            IsActive = true,
                            LastModifiedBy = "System",
                            MaxRedeemAmount = 100,
                            RedeemAmount = 0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Amount = 20m,
                            Code = "DISCOUNT20",
                            CreatedBy = "System",
                            CreatedOn = 17040672000000000L,
                            Description = "20% off your order",
                            ExpirationDate = 17356895990000000L,
                            IsActive = true,
                            LastModifiedBy = "System",
                            MaxRedeemAmount = 200,
                            RedeemAmount = 10,
                            RestaurantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
