global using BuildingBlocks.Entities.Contracts;
global using BuildingBlocks.Enums;
global using MediatR;
global using NodaTime;
global using Ordering.Domain.Abstractions;
global using Ordering.Domain.Events;
global using Ordering.Domain.Exceptions;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using Abstractions = Ordering.Domain.Abstractions;