// <auto-generated />
using System;
using Kitchen.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchen.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KitchenDbContext))]
    [Migration("20260706233256_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt", "OccurredOn")
                        .HasDatabaseName("ix_outbox_messages_dispatched_at_occurred_on");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Kitchen.API.Domain.Aggregates.KitchenStation.KitchenStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("RestaurantId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "IsActive");

                    b.ToTable("kitchen_stations", (string)null);
                });

            modelBuilder.Entity("Kitchen.API.Domain.Aggregates.KitchenTicket.KitchenTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Instant?>("BumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BumpedAt");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CancellationReason");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CancelledAt");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("CancelledByUserId");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ConfirmedByUserId");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("OrderNumber");

                    b.Property<Instant?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReadyAt");

                    b.Property<Instant>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReceivedAt");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("RestaurantId");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Status");

                    b.ToTable("kitchen_tickets", (string)null);
                });

            modelBuilder.Entity("Kitchen.API.Domain.Aggregates.KitchenTicket.KitchenTicket", b =>
                {
                    b.OwnsMany("Kitchen.API.Domain.Aggregates.KitchenTicket.KitchenTicketItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<string[]>("Customizations")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("Customizations");

                            b1.Property<Guid>("KitchenTicketId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("MenuItemId");

                            b1.Property<string>("MenuItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("MenuItemName");

                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("OrderItemId");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("Quantity");

                            b1.Property<Instant?>("ReadyAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ReadyAt");

                            b1.Property<int?>("SeatNumber")
                                .HasColumnType("integer")
                                .HasColumnName("SeatNumber");

                            b1.Property<string[]>("SelectedVariations")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("SelectedVariations");

                            b1.Property<string>("SpecialInstructions")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SpecialInstructions");

                            b1.Property<Instant?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartedAt");

                            b1.Property<Guid?>("StationId")
                                .HasColumnType("uuid")
                                .HasColumnName("StationId");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("Status");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("Id");

                            b1.HasIndex("KitchenTicketId");

                            b1.ToTable("kitchen_ticket_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("KitchenTicketId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
