global using BuildingBlocks.Behaviors;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Entities.Interfaces;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Exceptions.Handler;
global using Basket.API.Models;
global using Models = global::Basket.API.Models;
global using Carter;
global using FluentValidation;
global using Mapster;
global using Marten;
global using MediatR;
global using NodaTime;