services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  kitchendb:
    image: postgres

  messagebroker:
    image: rabbitmq:3-management

  discountdb:
    image: postgres:16-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    depends_on:
      discountdb:
        condition: service_healthy

  identitydb:
    image: postgres

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  kitchen.api:
    image: ${DOCKER_REGISTRY-}kitchenapi
    build:
      context: .
      dockerfile: Services/Kitchen/Kitchen.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:

  postgres_basket:

  postgres_identity:

  postgres_kitchen:

  mssql_order:

  discount-data:
