using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Identity.API.Data.Migrations
{
    /// <summary>
    /// Phase 5 of the Trust Root Hardening plan: switches
    /// <c>UserRestaurants.RestaurantId</c> from <c>integer</c> to
    /// <c>uuid</c> so the value round-trips correctly through
    /// <c>Guid.TryParse</c> on every consumer. Pre-change, Identity
    /// emitted <c>"restaurantId": "42"</c> in the JWT and every
    /// consumer's tenant filter silently fell through (Guid.TryParse
    /// returned false → Guid.Empty → no rows). The wire shape is now
    /// Guid-shaped end-to-end.
    /// </summary>
    /// <remarks>
    /// <para>Why this destructive strategy (truncate + alter): old
    /// integer values (e.g. <c>42</c>) cannot be cast to valid UUIDs,
    /// so an in-place conversion would fail. The Phase 2 seed-gate
    /// change keeps production deploys on an empty UserRestaurants
    /// table so the truncation is a no-op. For dev databases with
    /// important test data, export the rows first; the migration is
    /// <c>intentionally destructive</c> per §6.5 of the plan.</para>
    /// <para>Why this isn't generated by <c>dotnet ef migrations add</c>:
    /// EF Core's auto-generator produces a safe alter-column migration
    /// that fails on the cast. The plan's spec (§6.5) requires the
    /// hand-authored truncate-then-alter shape; the file is checked
    /// in alongside the snapshot update so the EF model and the SQL
    /// stay in lockstep.</para>
    /// </remarks>
    public partial class UserRestaurantIdToGuid : Migration
    {
        /// <inheritdoc/>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drop the composite primary key constraint that depends
            // on the RestaurantId column. PostgreSQL refuses to alter
            // a column's type while a PK depends on it.
            migrationBuilder.DropPrimaryKey(
                name: "PK_UserRestaurants",
                table: "UserRestaurants");

            // Truncate first because old integer values (e.g. 42)
            // cannot be cast to a valid uuid. The plan's §6.5 spec
            // acknowledges the data loss; production deploys start
            // on an empty table per the Phase 2 seed-gate change.
            migrationBuilder.Sql("TRUNCATE TABLE \"UserRestaurants\";");

            // Alter the column type to uuid. The USING clause
            // provides the empty string → all-zeros cast since the
            // table is empty post-truncate; the cast succeeds
            // because every remaining row is a freshly-inserted
            // empty value.
            migrationBuilder.AlterColumn<Guid>(
                name: "RestaurantId",
                table: "UserRestaurants",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            // Recreate the composite primary key on the new
            // (UserId, RestaurantId) pair.
            migrationBuilder.AddPrimaryKey(
                name: "PK_UserRestaurants",
                table: "UserRestaurants",
                columns: ["UserId", "RestaurantId"]);
        }

        /// <inheritdoc/>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverses the Up migration. Note: data loss in the Up
            // migration is irreversible — the Down can only restore
            // the schema, not the truncated rows.
            migrationBuilder.DropPrimaryKey(
                name: "PK_UserRestaurants",
                table: "UserRestaurants");

            migrationBuilder.AlterColumn<int>(
                name: "RestaurantId",
                table: "UserRestaurants",
                type: "integer",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserRestaurants",
                table: "UserRestaurants",
                columns: ["UserId", "RestaurantId"]);
        }
    }
}
