// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Identity.API.Data.Migrations
{
    public partial class IdentityDbContextModel
    {
        private IdentityDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("461da9d5-c039-4ce9-87e4-f94444fda465"), entityTypeCount: 15)
        {
        }

        partial void Initialize()
        {
            var applicationRole = ApplicationRoleEntityType.Create(this);
            var applicationUser = ApplicationUserEntityType.Create(this);
            var loginAuditLog = LoginAuditLogEntityType.Create(this);
            var permission = PermissionEntityType.Create(this);
            var rolePermission = RolePermissionEntityType.Create(this);
            var userRestaurant = UserRestaurantEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);
            var openIddictEntityFrameworkCoreApplication = OpenIddictEntityFrameworkCoreApplicationEntityType.Create(this);
            var openIddictEntityFrameworkCoreAuthorization = OpenIddictEntityFrameworkCoreAuthorizationEntityType.Create(this);
            var openIddictEntityFrameworkCoreScope = OpenIddictEntityFrameworkCoreScopeEntityType.Create(this);
            var openIddictEntityFrameworkCoreToken = OpenIddictEntityFrameworkCoreTokenEntityType.Create(this);

            LoginAuditLogEntityType.CreateForeignKey1(loginAuditLog, applicationUser);
            RolePermissionEntityType.CreateForeignKey1(rolePermission, permission);
            RolePermissionEntityType.CreateForeignKey2(rolePermission, applicationRole);
            UserRestaurantEntityType.CreateForeignKey1(userRestaurant, applicationUser);
            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, applicationRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, applicationUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, applicationUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, applicationRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, applicationUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, applicationUser);
            OpenIddictEntityFrameworkCoreAuthorizationEntityType.CreateForeignKey1(openIddictEntityFrameworkCoreAuthorization, openIddictEntityFrameworkCoreApplication);
            OpenIddictEntityFrameworkCoreTokenEntityType.CreateForeignKey1(openIddictEntityFrameworkCoreToken, openIddictEntityFrameworkCoreApplication);
            OpenIddictEntityFrameworkCoreTokenEntityType.CreateForeignKey2(openIddictEntityFrameworkCoreToken, openIddictEntityFrameworkCoreAuthorization);

            ApplicationRoleEntityType.CreateAnnotations(applicationRole);
            ApplicationUserEntityType.CreateAnnotations(applicationUser);
            LoginAuditLogEntityType.CreateAnnotations(loginAuditLog);
            PermissionEntityType.CreateAnnotations(permission);
            RolePermissionEntityType.CreateAnnotations(rolePermission);
            UserRestaurantEntityType.CreateAnnotations(userRestaurant);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);
            OpenIddictEntityFrameworkCoreApplicationEntityType.CreateAnnotations(openIddictEntityFrameworkCoreApplication);
            OpenIddictEntityFrameworkCoreAuthorizationEntityType.CreateAnnotations(openIddictEntityFrameworkCoreAuthorization);
            OpenIddictEntityFrameworkCoreScopeEntityType.CreateAnnotations(openIddictEntityFrameworkCoreScope);
            OpenIddictEntityFrameworkCoreTokenEntityType.CreateAnnotations(openIddictEntityFrameworkCoreToken);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
