// <auto-generated />
using Identity.API.Data;
using Identity.API.Data.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(IdentityDbContext), typeof(IdentityDbContextModel))]
